---
### Pandoc's LaTeX options
linkcolor: black
urlcolor: black
citecolor: black
documentclass: book
fontsize: 11
papersize: b5paper
secnumdepth: 3
mainfont: SourceHanSans-Regular
sansfont: SourceHanSans-Regular
monofont: RictyDiminished-Regular
mainlang: Japanese
mathfont: SourceHanSans-Regular
CJKmainfont: SourceHanSans-Normal
CJKsansfont: SourceHanSans-Normal
CJKmonofont: RictyDiminished-Regular
geometry: "top=30truemm,bottom=30truemm,left=20truemm,right=20truemm"

### pandoc-crossref options
listings: true
secPrefix: Chapter
codeBlockCaptions: true
nameInLink: true
figureTitle: "^~&#9650;~^Figure"
tableTitle: "~^&#9660;^~Table"
listingTitle: "~^&#9660;^~List"

### extra LaTeX template options
tables: true
chapters: true

### pandocker-lua-filters options
#lgeometry: "top=20truemm,bottom=20truemm,left=20truemm,right=20truemm"
#include: [markdown, images, data, Out]
...
