---
### Pandoc's LaTeX options
linkcolor: black
urlcolor: black
citecolor: black
documentclass: bxjsbook
classoption:
  - xelatex
  - pandoc
  - jafont=haranoaji
  - ja=standard
  - textwidth=45zw
  - number-of-lines=38
  - base=10pt
  - openany
watermarkoption:
  - contents=
fontsize: 10
papersize: b5
secnumdepth: 3
mainfont: HaranoAjiGothic-Regular.otf
mainfontoptions:
  - AutoFakeSlant=0.2
  - AutoFakeBold
sansfont: HaranoAjiGothic-Regular.otf
sansfontoptions:
  - AutoFakeSlant=0.2
  - AutoFakeBold
monofont: RictyDiminished-Regular
monofontoptions:
  - Scale=MatchLowercase
  - Mapping=tex-ansi
  - AutoFakeBold
mainlang: Japanese
mathfont: HaranoAjiGothic-Regular.otf
CJKmainfont: HaranoAjiGothic-Regular.otf
CJKsansfont: HaranoAjiGothic-Regular.otf
CJKmonofont: RictyDiminished-Regular
CJKoptions:
  - AutoFakeSlant=0.2
  - AutoFakeBold
#geometry: "top=30truemm,bottom=30truemm,left=20truemm,right=20truemm"

### pandoc-crossref options
listings: true
secPrefix: Chapter
codeBlockCaptions: true
nameInLink: true
figureTitle: "^~&#9650;~^ Figure"
tableTitle: "~^&#9660;^~ Table"
listingTitle: "~^&#9660;^~ List"

### extra LaTeX template options
tables: true
chapters: true

### pandocker-lua-filters options
lgeometry: "top=30truemm,bottom=30truemm,left=20truemm,right=20truemm"
#include: [markdown, images, data, Out]
...
