---
### Pandoc's LaTeX options
linkcolor: black
urlcolor: black
citecolor: black
documentclass: bxjsbook
classoption:
  - xelatex
  - pandoc
  - jafont=noto-jp
  - ja=standard
  - textwidth=45zw
  - number-of-lines=38
  - base=10pt
  - openany
fontsize: 10
papersize: b5
secnumdepth: 3
mainfont: SourceHanSans-Regular
mainfontoptions:
  - AutoFakeSlant=0.2
sansfont: SourceHanSans-Regular
monofont: RictyDiminished-Regular
monofontoptions:
  - Scale=MatchLowercase
  - Mapping=tex-ansi
mainlang: Japanese
mathfont: SourceHanSans-Regular
CJKmainfont: SourceHanSans-Normal
CJKsansfont: SourceHanSans-Normal
CJKmonofont: RictyDiminished-Regular
CJKoptions:
  - AutoFakeSlant=0.2
  - AutoFakeBold
#geometry: "top=30truemm,bottom=30truemm,left=20truemm,right=20truemm"

### pandoc-crossref options
listings: true
secPrefix: Chapter
codeBlockCaptions: true
nameInLink: true
figureTitle: "^~&#9650;~^ Figure"
tableTitle: "~^&#9660;^~ Table"
listingTitle: "~^&#9660;^~ List"

### extra LaTeX template options
tables: true
chapters: true

### pandocker-lua-filters options
lgeometry: "top=30truemm,bottom=30truemm,left=20truemm,right=20truemm"
#include: [markdown, images, data, Out]
...
