---
documentclass: book
secPrefix: Chapter
linkcolor: black
urlcolor: black
citecolor: black
chapter: true
listings: true
tables: true
codeBlockCaptions: true
listingTitle: "List"
# date: 本の出版日時

fontsize: 11
papersize: b5paper
secnumdepth: 3
mainfont: SourceHanSans-Regular
sansfont: SourceHanSans-Regular
monofont: NotoSansMono-Regular
mainlang: Japanese
mathfont: SourceHanSans-Light
CJKmainfont: SourceHanSans-Normal
CJKsansfont: SourceHanSans-Normal
CJKmonofont: NotoSansMono-Regular
geometry: "top=30truemm,bottom=30truemm,left=20truemm,right=20truemm"
lgeometry: "top=20truemm,bottom=20truemm,left=20truemm,right=20truemm"

include: [markdown, images, data, Out]
...
