---
title: 私的Markdown-PDF変換環境を紹介する本
abstract: Pandocはいいぞ
circle: KY技研
author: "@_K4ZUKI_"
comiket: 技術書典3
year: 2017
publisher: キンコーズで印刷製本
docrevision: "1.0"
front: images/front-image.png
verbcolored: false
# rmnote: false
...
